- name: Satellite / Foreman Detection
  vars:                                                                               # Change this if the foreman hostname changes
    hostname_foreman: "hostname = pforemanws01v.rete.poste"
  hosts: testing                                                                      # Change this host wave as you need
  tasks:

    - name: Gathering RHSM Hostname                                                   # Cat the rhsm conf file, retrieving hostname
      ansible.builtin.shell: set -o pipefail && cat /etc/rhsm/rhsm.conf | grep -w 'hostname ='
      register: rhsm_hostname
      changed_when: false
      failed_when: false

    - name: Determining the registration type                                         # "If" statements to determine the registration type
      ansible.builtin.set_fact:
        registration_type: >-                                                         # Readability for the jinja2 script
          {% if hostname_foreman == rhsm_hostname.stdout %}
          REGISTERED
          {% elif not hostname_foreman == rhsm_hostname.stdout %}
          NOT_REGISTERED
          {% endif %}

    - name: Giving Output Information                                                 # Creating the Output debug for easy info access
      ansible.builtin.debug:
        msg:
          hostname: "{{ ansible_facts['fqdn'] }}"
          register: "{{ registration_type }}"
