- name: Satellite / Foreman Detection
  vars:
    hostname_foreman: "hostname = pforemanws01v.rete.poste"
  hosts: testing
  tasks:

    - name: Gathering RHSM Hostname
      ansible.builtin.shell: set -o pipefail && cat /etc/rhsm/rhsm.conf | grep -w 'hostname ='
      register: rhsm_hostname
      changed_when: false
      failed_when: false

    - name: Determining the registration type
      ansible.builtin.set_fact:
        registration_type: >-
          {% if hostname_foreman == rhsm_hostname.stdout %}
          FOREMAN
          {% elif not hostname_foreman == rhsm_hostname.stdout %}
          SATELLITE
          {% endif %}

    - name: Giving Output Information
      ansible.builtin.debug:
        msg:
          hostname: "{{ ansible_facts['fqdn'] }}"
          register: "{{ registration_type }}"

    - name: Registration Collection
      ansible.builtin.set_fact:
        registration_collection: "{{ registration_type }}"

- name: Play for Counting
  hosts: all
  run_once: true
  gather_facts: false
  tasks:

    - name: Counting Foreman
      ansible.builtin.set_fact:
        foreman_count: >-
          {{ groups['all']
          | map('extract', hostvars, 'registration_collection')
          | select('equalto', ' FOREMAN ')
          | list
          | length }}

    - name: Counting Satellite
      ansible.builtin.set_fact:
        satellite_count: >-
          {{ groups['all']
          | map('extract', hostvars, 'registration_collection')
          | select('equalto', ' SATELLITE ')
          | list
          | length }}

    - name: Debugging summary
      ansible.builtin.debug:
        msg:
          Foreman Machines: "{{ foreman_count }}"
          Satellite Machines: "{{ satellite_count }}"
